server:
  port: 8001

spring:
  application:
    name: msc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangzhf/config-repo-demo
          username: wangzhf
          password: abcd
          # Git仓库下的相对地址，可以配置多个，用逗号分隔
          # search-paths: dir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
