spring:
  application:
    name: msc-monitor-zipkin
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      rate: 50
      probability: 1.0

server:
  port: 9020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
