spring:
  application:
    name: msc-gateway-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

# 默认会代理eureka上所有注册的服务
zuul:
  routes:
    hello:
      # 映射
      # path: /api/**
      # 指定转发地址
      # url: http://localhost:9000/user/
      # 指定转发到服务
      # serviceId: msc-apis-users
  # 配置失败重试
  retryable: true

ribbon:
  # 对当前服务的重试次数
  MaxAutoRetries: 2
  # 切换相同Server的次数
  MaxAutoRetriesNextServer: 0



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
