spring:
  application:
    name: msc-apis-users
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/